// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ8V5izpxXrmAyWcK0OPPEimMflawPavQ',
    appId: '1:333224010311:web:11ee345e6b5f7f0b218762',
    messagingSenderId: '333224010311',
    projectId: 'powertaxi-metro',
    authDomain: 'powertaxi-metro.firebaseapp.com',
    storageBucket: 'powertaxi-metro.firebasestorage.app',
    measurementId: 'G-V135CKG2CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyr_jTH71VPbafhGCZDaXrM1GG1k7d8Ls',
    appId: '1:333224010311:android:01416aa1f47bda70218762',
    messagingSenderId: '333224010311',
    projectId: 'powertaxi-metro',
    storageBucket: 'powertaxi-metro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu8jre-FuAolCZRMEUas8g7wH5buVJZwM',
    appId: '1:333224010311:ios:4c44ad42cdbedca9218762',
    messagingSenderId: '333224010311',
    projectId: 'powertaxi-metro',
    storageBucket: 'powertaxi-metro.firebasestorage.app',
    iosBundleId: 'com.example.powertaxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu8jre-FuAolCZRMEUas8g7wH5buVJZwM',
    appId: '1:333224010311:ios:4c44ad42cdbedca9218762',
    messagingSenderId: '333224010311',
    projectId: 'powertaxi-metro',
    storageBucket: 'powertaxi-metro.firebasestorage.app',
    iosBundleId: 'com.example.powertaxi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ8V5izpxXrmAyWcK0OPPEimMflawPavQ',
    appId: '1:333224010311:web:e92de323f7a47c32218762',
    messagingSenderId: '333224010311',
    projectId: 'powertaxi-metro',
    authDomain: 'powertaxi-metro.firebaseapp.com',
    storageBucket: 'powertaxi-metro.firebasestorage.app',
    measurementId: 'G-G1CSHZJB36',
  );
}
